In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('carprices.csv')
df.head()

Car Model  Mileage  Sell Price($)  Age(yrs)
0    BMW X5    69000          18000         6
1    BMW X5    35000          34000         3
2    BMW X5    57000          26100         5
3    BMW X5    22500          40000         2
4    BMW X5    46000          31500         4

In [3]:
df.isnull().sum()

Car Model        0
Mileage          0
Sell Price($)    0
Age(yrs)         0
dtype: int64

In [7]:
#now doing onehotcoder with the help of pandas function get_dummies() method
df_encoder= pd.get_dummies(df['Car Model'],prefix='Car Model')
df_encoder=df_encoder.astype('int')
df_encoder

Car Model_Audi A5  Car Model_BMW X5  Car Model_Mercedez Benz C class
0                   0                 1                                0
1                   0                 1                                0
2                   0                 1                                0
3                   0                 1                                0
4                   0                 1                                0
5                   1                 0                                0
6                   1                 0                                0
7                   1                 0                                0
8                   1                 0                                0
9                   0                 0                                1
10                  0                 0                                1
11                  0                 0                                1
12                  0                 0                                1

In [9]:
#now merage the both the data set 
merage = pd.concat([df,df_encoder],axis=1)
merage

Car Model  Mileage  Sell Price($)  Age(yrs)  \
0                  BMW X5    69000          18000         6   
1                  BMW X5    35000          34000         3   
2                  BMW X5    57000          26100         5   
3                  BMW X5    22500          40000         2   
4                  BMW X5    46000          31500         4   
5                 Audi A5    59000          29400         5   
6                 Audi A5    52000          32000         5   
7                 Audi A5    72000          19300         6   
8                 Audi A5    91000          12000         8   
9   Mercedez Benz C class    67000          22000         6   
10  Mercedez Benz C class    83000          20000         7   
11  Mercedez Benz C class    79000          21000         7   
12  Mercedez Benz C class    59000          33000         5   

    Car Model_Audi A5  Car Model_BMW X5  Car Model_Mercedez Benz C class  
0                   0                 1                                0  
1                   0                 1                                0  
2                   0                 1                                0  
3                   0                 1                                0  
4                   0                 1                                0  
5                   1                 0                                0  
6                   1                 0                                0  
7                   1                 0                                0  
8                   1                 0                                0  
9                   0                 0                                1  
10                  0                 0                                1  
11                  0                 0                                1  
12                  0                 0                                1

In [12]:
final_df = merage.drop(['Car Model','Car Model_Mercedez Benz C class'],axis=1)
final_df

Mileage  Sell Price($)  Age(yrs)  Car Model_Audi A5  Car Model_BMW X5
0     69000          18000         6                  0                 1
1     35000          34000         3                  0                 1
2     57000          26100         5                  0                 1
3     22500          40000         2                  0                 1
4     46000          31500         4                  0                 1
5     59000          29400         5                  1                 0
6     52000          32000         5                  1                 0
7     72000          19300         6                  1                 0
8     91000          12000         8                  1                 0
9     67000          22000         6                  0                 0
10    83000          20000         7                  0                 0
11    79000          21000         7                  0                 0
12    59000          33000         5                  0                 0

In [15]:
X = final_df.drop('Sell Price($)',axis = 1)
X

Mileage  Age(yrs)  Car Model_Audi A5  Car Model_BMW X5
0     69000         6                  0                 1
1     35000         3                  0                 1
2     57000         5                  0                 1
3     22500         2                  0                 1
4     46000         4                  0                 1
5     59000         5                  1                 0
6     52000         5                  1                 0
7     72000         6                  1                 0
8     91000         8                  1                 0
9     67000         6                  0                 0
10    83000         7                  0                 0
11    79000         7                  0                 0
12    59000         5                  0                 0

In [16]:
y = final_df['Sell Price($)']
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Sell Price($), dtype: int64

In [17]:
#now making the model using the linear Regression
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [18]:
model.fit(X,y)

LinearRegression()

In [25]:
model.predict([[45000,4,1,0]])

C:\Users\91952\anaconda3\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([34537.77647335])

In [24]:
model.predict([[69000,6,0,1]])

C:\Users\91952\anaconda3\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([18705.2723644])

In [23]:
model.predict([[45000,4,0,0]])

C:\Users\91952\anaconda3\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([36991.31721061])

In [27]:
model.score(X,y)

0.9417050937281082

In [28]:
#now using the Sklearn.preprocessing method for onehotcoder
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()


In [35]:
new_df = df
new_df.head()

Car Model  Mileage  Sell Price($)  Age(yrs)
0    BMW X5    69000          18000         6
1    BMW X5    35000          34000         3
2    BMW X5    57000          26100         5
3    BMW X5    22500          40000         2
4    BMW X5    46000          31500         4

In [41]:
new_df['Car Model'] = ohe.fit_transform(new_df['Car Model'])


ValueError: Expected 2D array, got 1D array instead:
array=['BMW X5' 'BMW X5' 'BMW X5' 'BMW X5' 'BMW X5' 'Audi A5' 'Audi A5'
 'Audi A5' 'Audi A5' 'Mercedez Benz C class' 'Mercedez Benz C class'
 'Mercedez Benz C class' 'Mercedez Benz C class'].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [39]:
ohe_df = pd.DataFrame(ohe_result.toarray(), columns=ohe.get_feature_names(['Car Model']))

AttributeError: 'OneHotEncoder' object has no attribute 'get_feature_names'