In [2]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
import numpy as np

In [3]:
iris = load_iris()

# Logistic Regression

In [21]:
lr=cross_val_score(LogisticRegression(),iris.data,iris.target)
lr

C:\Users\91952\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [22]:
np.average(lr)

0.9733333333333334

# RandomForestClassifier

In [19]:
rfc=cross_val_score(RandomForestClassifier(),iris.data,iris.target)
rfc

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [20]:
np.average(rfc)

0.9666666666666668

In [17]:
rfc_=cross_val_score(RandomForestClassifier(n_estimators=60),iris.data,iris.target)
rfc_

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [18]:
np.average(rfc_)

0.9666666666666668

# SVC

In [14]:
svc=cross_val_score(SVC(),iris.data,iris.target)
svc

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [15]:
np.average(svc)

0.9666666666666666

# DecisionTreeClassifier

In [11]:
dtc=cross_val_score(DecisionTreeClassifier(),iris.data,iris.target)

In [12]:
dtc

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [13]:
np.average(dtc)

0.9600000000000002